yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        "signup/",
        views.SignUp.as_view(template_name='users/signup.html'),
        name="signup"
    ),
    path(
        "logout/",
        LogoutView.as_view(
            template_name="users/logged_out.html"),
        name="logout"
    ),
    path(
        "login/",
        LoginView.as_view(
            template_name="users/login.html"),
        name="login"
    ),
    path(
        "auth/password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html"),
        name="password_change_form",
    ),
    path(
        "auth/password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"),
        name="password_change_done"
    ),
    path(
        "auth/password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html"),
        name="password_reset"
    ),
    path(
        "auth/password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"),
        name="password_reset_done"),
    path(
        "auth/reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"),
        name="confirm"
    ),
    path(
        "auth/reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"),
        name="password_reset_complete"
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/article.html
{% load thumbnail %}    
    {% if not forloop.last %}<hr>{% endif %}
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
            {% if all_user_post_link %}<a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>{% endif %}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
        </li>
    </ul>
    <ul>
        <li>
            {% if detail_info_link %}<a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>{% endif %}
        </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if post.group and group_list_link %}<a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы {{ post.group }}</a>{% endif %}
</article>

yatube/templates/includes/errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
    {{ error|escape }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
    {{ error|escape }}
</div>
{% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<nav class="border-top text-center py-3">
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</nav>

yatube/templates/includes/form.html
{% load user_filters %}
<div class="form-group row my-3">
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
        <span class="required text-danger">*</span>
        {% endif %}
    </label>
    {{ field|addclass:'form-control' }}
    {% if field.help_text %}
    <small
            id="{{ field.id_for_label }}-help"
            class="form-text text-muted">
        {{ field.help_text|safe }}
    </small>
    {% endif %}
</div>

yatube/templates/includes/header.html
{% load static %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span style="color:red">Ya</span>tube
            </a>
            {# Добавлено в спринте #}

            {% comment %}
            Меню - список пунктов со стандартными классами Bootsrap.
            Класс nav-pills нужен для выделения активных пунктов
            {% endcomment %}
            <ul class="nav nav-pills">
                {% with request.resolver_match.view_name as view_name %}
                <li class="nav-item">
                    <a class="nav-link {% if request.resolver_match.view_name  == 'about:author' %}active{% endif %}"
                       href="{% url 'about:author' %}"
                    >
                        Об авторе
                    </a>
                </li>
                {% endwith %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about:tech' %}">Технологии</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light">Изменить пароль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
                </li>
                <li>
                    Пользователь: {{ user.username }}
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
                </li>
                {% endif %}
            </ul>
            {# Конец добавленого в спринте #}
        </div>
    </nav>